language:      node_js
git:
  depth:       3
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules
notifications:
<<<<<<< HEAD
  email:       false
=======
  email:       false
>>>>>>> 0c5c49124d3449a8c938534496f241d5bfc03e5b
