import type { Metadata } from 'next'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import '../../../css/business-casual.min.css'

import BootstrapClient from './BootstrapClient'
import Navigation from '@/components/Navigation'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <meta charSet='utf-8' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, shrink-to-fit=no'
        />
        <meta name='description' content='' />
        <meta name='author' content='' />
        <link
          rel='icon'
          href='./img/hamburger-icon-10.jpg'
          type='image/x-icon'
        />

        <title>Hi-Mountain</title>

        {/* <!-- Custom fonts for this template --> */}
        <link
          href='https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i'
          rel='stylesheet'
        />
        <link
          href='https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i'
          rel='stylesheet'
        />
      </head>
      <body>
        <BootstrapClient />
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
